apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
commonLabels:
  env: int
  app: commerce-services
namePrefix: int-
bases:
  - ../base
resources:
  - namespace.yaml
patchesStrategicMerge:
  - api-ingress.yaml
  - static-ingress.yaml