apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  env: prod
  app: commerce-services
namePrefix: prod-
bases:
  - ../base
resources:
  - namespace.yaml
patchesStrategicMerge:
  - api-ingress.yaml
  - static-ingress.yaml
