apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: commerce-services-api
  labels:
    service: api
    app: commerce-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: commerce-services-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 1000