# https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-services-static
  labels:
    service: static
  annotations:
    eks.amazonaws.com/role-arn: # arn
secrets:
  - name: # token